name: Update webhooks

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/update-webhooks.yml"
      - "webhooks/**"
      - "Dockerfile"

jobs:
  build:
    name: Build Image
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Load GitHub Token from 1Password
        id: op-github-token
        uses: 1password/load-secrets-action@581a835fb51b8e7ec56b71cf2ffddd7e68bb25e0 # v2
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          SECRET: op://ohxdgpsykiqhfslndgzsmfittq/rwuztfo6ozy46ve4gg7otupngy/token

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ steps.op-github-token.outputs.SECRET }}

      - name: Build the docker image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:${{ github.sha }} --tag ghcr.io/${{ github.repository }}:latest

      - name: Push the docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}:latest
