name: Update webhooks

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/update-webhooks.yml"
      - "webhooks/**"
      - "Dockerfile"

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4


      # - name: Login to GitHub Container Registry

      # - name: Build the Docker image
      #   run: docker build . --file Dockerfile --tag webhook-with-docker:$(git rev-parse --short HEAD)
